# Hair Segmentation Configuration - SegFormer

# Model settings
model:
  name: "segformer"
  model_id: "jonathandinu/face-parsing"  # HuggingFace model ID
  num_classes: 19
  hair_class_index: 17  # Will be auto-detected if hair class name differs

# Image processing
image:
  input_size: [512, 512]  # [height, width] - SegFormer can handle any size

# Post-processing (same as before)
postprocess:
  # Morphological operations
  morph_kernel_size: 5
  morph_iterations: 2

  # Mask refinement
  apply_gaussian_blur: true
  gaussian_kernel_size: 5

  # Threshold for binary mask
  confidence_threshold: 0.5

# Output settings
output:
  save_alpha: true  # Always save with transparent background

# Processing
device: "cpu"  # "cuda" or "cpu"
batch_size: 1